---

services: docker

install:
  - pip install flask
  - pip install moto

env:
  - distro: ubuntu1404
  - distro: ubuntu1604

script:
  # Run tests.
  - ${PWD}/tests/test.sh

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
