---
  - block:
    - name: Check if CWA Agent is installed
      stat: path=/opt/aws/amazon-cloudwatch-agent/bin
      register: cwa_bin_dir

    - include_tasks: install.yml
      when: not cwa_bin_dir.stat.exists
    when: cwa_agent_install

  - block:
    - name: Configure AWS CloudWatch Agent
      template:
        src: amazon-cloudwatch-agent.j2
        dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
        owner: root
        group: root
        mode: 0600
      notify: restart cwa agent

    - name: Verify AWS CloudWatch Agent Config for EC2
      command: /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
      become: yes
      when: ec2_region is defined

    - name: start and enable cwa-agent service
      service: name=amazon-cloudwatch-agent state=started enabled=yes
      when: ansible_distribution_release == 'trusty'

    - name: Start and enable cwa-agent systemd service
      systemd: name=amazon-cloudwatch-agent state=started enabled=yes daemon_reload=yes
      when: ansible_distribution_release == 'xenial' or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    when: cwa_agent_manage
